// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package delayq

import (
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

// Options should use newConfig to initialize it
type Options struct {
	// annotation@Name(comment="名称")
	Name string
	// annotation@Prefix(comment="前缀")
	Prefix string
	// annotation@RedisScriptBuilder(comment="redis 脚本工厂")
	RedisScriptBuilder RedisScriptBuilder
	// annotation@RetryTimes(comment="重试次数")
	RetryTimes int
	// annotation@OnDeadLetter(comment="当有死信")
	OnDeadLetter func(item *Item)
	// annotation@MonitorCounter(comment="监控统计函数")
	MonitorCounter func(metric string, value int64, labels prometheus.Labels)
	// annotation@Logger(comment="日志实现，默认输出到 stderr")
	Logger Logger
	// annotation@MaxConcurrency(comment="单 topic 业务处理最大并发 goroutine 数，<=0 表示不限制")
	MaxConcurrency int
	// annotation@VisibilityTimeout(comment="Redis 队列：item 被 poll 拉走后多久未 ack 视为失败被 reclaim")
	VisibilityTimeout time.Duration
	// annotation@RetryInterval(comment="基础重试间隔；下次重试时间 = now + RetryInterval * RetryBackoff^failedCount，且不超过 MaxRetryInterval")
	RetryInterval time.Duration
	// annotation@RetryBackoff(comment="重试退避系数，<=1 表示不退避（固定间隔）")
	RetryBackoff float64
	// annotation@MaxRetryInterval(comment="重试间隔上限")
	MaxRetryInterval time.Duration
	// annotation@RetryIntervalFunc(comment="自定义重试间隔函数，传入失败次数（>=1），返回下次重试延迟；非 nil 时优先于 RetryInterval/Backoff")
	RetryIntervalFunc func(failedCount int) time.Duration
}

// newConfig new Options
func newConfig(opts ...Option) *Options {
	cc := newDefaultOptions()
	for _, opt := range opts {
		opt(cc)
	}
	if watchDogOptions != nil {
		watchDogOptions(cc)
	}
	return cc
}

// ApplyOption apply multiple new option
func (cc *Options) ApplyOption(opts ...Option) {
	for _, opt := range opts {
		opt(cc)
	}
}

// Option option func
type Option func(cc *Options)

// WithName 名称
func WithName(v string) Option {
	return func(cc *Options) {
		cc.Name = v
	}
}

// WithPrefix 前缀
func WithPrefix(v string) Option {
	return func(cc *Options) {
		cc.Prefix = v
	}
}

// WithRedisScriptBuilder redis 脚本工厂
func WithRedisScriptBuilder(v RedisScriptBuilder) Option {
	return func(cc *Options) {
		cc.RedisScriptBuilder = v
	}
}

// WithRetryTimes 重试次数
func WithRetryTimes(v int) Option {
	return func(cc *Options) {
		cc.RetryTimes = v
	}
}

// WithOnDeadLetter 当有死信
func WithOnDeadLetter(v func(item *Item)) Option {
	return func(cc *Options) {
		cc.OnDeadLetter = v
	}
}

// WithMonitorCounter 监控统计函数
func WithMonitorCounter(v func(metric string, value int64, labels prometheus.Labels)) Option {
	return func(cc *Options) {
		cc.MonitorCounter = v
	}
}

// WithLogger 日志实现，默认输出到 stderr
func WithLogger(v Logger) Option {
	return func(cc *Options) {
		cc.Logger = v
	}
}

// WithMaxConcurrency 单 topic 业务处理最大并发 goroutine 数，<=0 表示不限制
func WithMaxConcurrency(v int) Option {
	return func(cc *Options) {
		cc.MaxConcurrency = v
	}
}

// WithVisibilityTimeout Redis 队列：item 被 poll 拉走后多久未 ack 视为失败被 reclaim
func WithVisibilityTimeout(v time.Duration) Option {
	return func(cc *Options) {
		cc.VisibilityTimeout = v
	}
}

// WithRetryInterval 基础重试间隔
func WithRetryInterval(v time.Duration) Option {
	return func(cc *Options) {
		cc.RetryInterval = v
	}
}

// WithRetryBackoff 重试退避系数，<=1 表示不退避（固定间隔）
func WithRetryBackoff(v float64) Option {
	return func(cc *Options) {
		cc.RetryBackoff = v
	}
}

// WithMaxRetryInterval 重试间隔上限
func WithMaxRetryInterval(v time.Duration) Option {
	return func(cc *Options) {
		cc.MaxRetryInterval = v
	}
}

// WithRetryIntervalFunc 自定义重试间隔函数，传入失败次数（>=1），返回下次重试延迟；非 nil 时优先于 RetryInterval/Backoff
func WithRetryIntervalFunc(v func(failedCount int) time.Duration) Option {
	return func(cc *Options) {
		cc.RetryIntervalFunc = v
	}
}

// InstallOptionsWatchDog the installed func will called when newConfig  called
func InstallOptionsWatchDog(dog func(cc *Options)) { watchDogOptions = dog }

// watchDogOptions global watch dog
var watchDogOptions func(cc *Options)

// newDefaultOptions new default Options
func newDefaultOptions() *Options {
	cc := &Options{}

	for _, opt := range [...]Option{
		WithName("delayq"),
		WithPrefix("__dq"),
		WithRedisScriptBuilder(nil),
		WithRetryTimes(10),
		WithOnDeadLetter(nil),
		WithMonitorCounter(func(metric string, value int64, labels prometheus.Labels) {
		}),
		WithLogger(nil),
		WithMaxConcurrency(256),
		WithVisibilityTimeout(10 * time.Minute),
		WithRetryInterval(1 * time.Second),
		WithRetryBackoff(1.0),
		WithMaxRetryInterval(60 * time.Second),
		WithRetryIntervalFunc(nil),
	} {
		opt(cc)
	}

	return cc
}

// all getter func
func (cc *Options) GetName() string                           { return cc.Name }
func (cc *Options) GetPrefix() string                         { return cc.Prefix }
func (cc *Options) GetRedisScriptBuilder() RedisScriptBuilder { return cc.RedisScriptBuilder }
func (cc *Options) GetRetryTimes() int                        { return cc.RetryTimes }
func (cc *Options) GetOnDeadLetter() func(item *Item)         { return cc.OnDeadLetter }
func (cc *Options) GetMonitorCounter() func(metric string, value int64, labels prometheus.Labels) {
	return cc.MonitorCounter
}
func (cc *Options) GetLogger() Logger                   { return cc.Logger }
func (cc *Options) GetMaxConcurrency() int              { return cc.MaxConcurrency }
func (cc *Options) GetVisibilityTimeout() time.Duration { return cc.VisibilityTimeout }
func (cc *Options) GetRetryInterval() time.Duration     { return cc.RetryInterval }
func (cc *Options) GetRetryBackoff() float64            { return cc.RetryBackoff }
func (cc *Options) GetMaxRetryInterval() time.Duration  { return cc.MaxRetryInterval }
func (cc *Options) GetRetryIntervalFunc() func(failedCount int) time.Duration {
	return cc.RetryIntervalFunc
}

// OptionsVisitor visitor interface for Options
type OptionsVisitor interface {
	GetName() string
	GetPrefix() string
	GetRedisScriptBuilder() RedisScriptBuilder
	GetRetryTimes() int
	GetOnDeadLetter() func(item *Item)
	GetMonitorCounter() func(metric string, value int64, labels prometheus.Labels)
	GetLogger() Logger
	GetMaxConcurrency() int
	GetVisibilityTimeout() time.Duration
	GetRetryInterval() time.Duration
	GetRetryBackoff() float64
	GetMaxRetryInterval() time.Duration
	GetRetryIntervalFunc() func(failedCount int) time.Duration
}

// OptionsInterface visitor + ApplyOption interface for Options
type OptionsInterface interface {
	OptionsVisitor
	ApplyOption(...Option)
}
