// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: item.proto

package delayq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item 延迟队列中的一条数据
type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主题
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// 延迟秒数（相对当前时间）。
	//
	// Push 时：负值视为 0（立即可执行）。
	//
	// Handler 接收时：当该 item 因失败重试再次派发时，DelaySecond 会被覆盖为
	// 负值用于编码已失败次数（如 -3 表示已失败 3 次）。
	// 用户的 handler 通常不应依赖此字段；如需观察重试次数，请记录业务侧 retry_count。
	DelaySecond int64 `protobuf:"varint,2,opt,name=delay_second,json=delaySecond,proto3" json:"delay_second,omitempty"`
	// 业务自定义负载，建议 <=1KB；Redis 模式下不可重复
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// 优先级（仅在同一执行时间点生效，越大越先执行）；默认 0
	Priority      int32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Item) GetDelaySecond() int64 {
	if x != nil {
		return x.DelaySecond
	}
	return 0
}

func (x *Item) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Item) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_item_proto protoreflect.FileDescriptor

const file_item_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"item.proto\x12\x06delayq\"q\n" +
	"\x04Item\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fdelay_second\x18\x02 \x01(\x03R\vdelaySecond\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriorityB&Z$github.com/sandwich-go/delayq;delayqb\x06proto3"

var (
	file_item_proto_rawDescOnce sync.Once
	file_item_proto_rawDescData []byte
)

func file_item_proto_rawDescGZIP() []byte {
	file_item_proto_rawDescOnce.Do(func() {
		file_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)))
	})
	return file_item_proto_rawDescData
}

var file_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_item_proto_goTypes = []any{
	(*Item)(nil), // 0: delayq.Item
}
var file_item_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_item_proto_init() }
func file_item_proto_init() {
	if File_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_proto_goTypes,
		DependencyIndexes: file_item_proto_depIdxs,
		MessageInfos:      file_item_proto_msgTypes,
	}.Build()
	File_item_proto = out.File
	file_item_proto_goTypes = nil
	file_item_proto_depIdxs = nil
}
